# Render Blueprint for Backend Deployment
services:
  - type: web
    name: closet-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false # This will be set manually in Render dashboard
      - key: FRONTEND_URL
        value: http://localhost:8081
